################################################################################
MLI_FILE		= cordova_in_app_browser.mli
## Name which will be used in -package with ocamlfind
LIB_NAME		= cordova-plugin-inappbrowser
################################################################################
